apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: "http"
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    io.kompose.service: {{ .Chart.Name }}
status:
  loadBalancer: {}