version: '3.9'

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs/${PROXY_CRT}:/etc/ssl/certs/diva.crt
      - ./certs/${PROXY_KEY}:/etc/ssl/private/diva.key
    ports:
      - ${PROXY_PORT}:443
    networks:
      - core

networks:
  core:
    name: core
