# Default values for urban-pulse-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

initContainers: {}

## @section Urban Pulse Adapter Parameters

## @param port This will set the port where service and deployment will be available
##
port: 4001
## @param resourceManagementUrl URL where the Resource Mangement Service is available
##
resourceManagementUrl: ""
## @param divaLakeHost Hostname of our DIVA Lake instance
##
divaLakeHost: ""
## @param divaLakePort Port of our DIVA Lake instance
##
divaLakePort: ""
## @param divaLakeUsername The DIVA Lake username
##
divaLakeUsername: ""
## @param divaLakePassword The DIVA Lake password
##
divaLakePassword: ""
## @param bucketName The name of the minIO bucket where the lake stores files
##
bucketName: "file-lake"
