apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    io.kompose.service: {{ .Chart.Name | quote }}
  name: {{ .Chart.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name | quote }}
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/core: "true"
        io.kompose.service: {{ .Chart.Name | quote }}
    spec:
      initContainers:
        - name: wait-for-resource-management
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          {{- if .Values.global.resourceManagementUrl }}
          args: ["while [ $(curl -sw '%{http_code}' {{ .Values.global.resourceManagementUrl }}/health -o /dev/null) -ne 404 ]; do sleep 5; echo 'Waiting for resource-management...'; done"]
          {{- else }}
          args: ["while [ $(curl -sw '%{http_code}' {{ .Values.resourceManagementUrl }}/health -o /dev/null) -ne 404 ]; do sleep 5; echo 'Waiting for resource-management...'; done"]
          {{- end }}
        - name: wait-for-asset-management
          image: curlimages/curl:latest
          command: ["/bin/sh","-c"]
          {{- if .Values.global.assetManagementUrl }}
          args: ["while [ $(curl -sw '%{http_code}' {{ .Values.global.assetManagementUrl }}/health -o /dev/null) -ne 404 ]; do sleep 5; echo 'Waiting for asset-management...'; done"]
          {{- else }}
          args: ["while [ $(curl -sw '%{http_code}' {{ .Values.assetManagementUrl }}/health -o /dev/null) -ne 404 ]; do sleep 5; echo 'Waiting for asset-management...'; done"]
          {{- end }}  
      containers:
        - env:
            - name: "PORT"
              value: {{ .Values.port | quote }}
            - name: "RESOURCE_MANAGEMENT_URL"
              {{- if .Values.global.resourceManagementUrl }}
              value: {{ .Values.global.resourceManagementUrl | quote }}
              {{- else }}
              value: {{ required "please provide resourceManagementUrl" .Values.resourceManagementUrl | quote }}
              {{- end }}
            - name: "ASSET_MANAGEMENT_URL"
              {{- if .Values.global.assetManagementUrl }}
              value: {{ .Values.global.assetManagementUrl | quote }}
              {{- else }}
              value: {{ required "please provide assetManagementUrl" .Values.assetManagementUrl | quote }}
              {{- end }}
          image: "ghcr.io/fraunhoferisst/diva/{{ .Chart.Name }}:{{ .Chart.AppVersion}}"
          name: {{ .Chart.Name | quote }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: "Always"
status: {}
