name: Build and publish %%name%% image

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "%%path%%/**"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "%%path%%/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: %%name%%
  IMAGE_VERSION: %%version%%
  DIVA_DOCKER_CONTEXT: %%context%%
  DIVA_DOCKERFILE_PATH: %%dockerfile%%
  SERVICE_PATH: %%path%%
  SERVICE_RELATIVE_PATH: %%relativePath%%

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          context: ${{ env.DIVA_DOCKER_CONTEXT }}
          file: ${{ env.DIVA_DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SERVICE_NAME=${{ env.SERVICE_RELATIVE_PATH }}
