# ####################################################################################################################
# Data Space Connector
# Example configuration for the DSC (https://github.com/International-Data-Spaces-Association/DataspaceConnector)
# ####################################################################################################################

version: '3.9'

services:
  dsc-postgres:
    image: postgres:13
    container_name: 'dsc-postgres'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DSC_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DSC_POSTGRES_PASSWORD}
      POSTGRES_DB: connectordb
    networks:
      - dsc
    volumes:
      - connector-data:/var/lib/postgresql/data

  dsc:
    container_name: 'dsc-connector'
    image: ghcr.io/international-data-spaces-association/dataspace-connector:5.2.1
    ports:
      - ${DSC_PORT}:${DSC_PORT}
    environment:
      SERVER_PORT: ${DSC_PORT}
      SPRING_SECURITY_USER_NAME: ${DSC_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${DSC_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://dsc-postgres:5432/connectordb
      SPRING_DATASOURCE_USERNAME: ${DSC_POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DSC_POSTGRES_PASSWORD}
      SPRING_DATASOURCE_PLATFORM: postgres
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    networks:
      - core
      - dsc
    depends_on:
      - dsc-postgres

volumes:
  connector-data: {}

networks:
  core:
    name: core
  dsc:
    name: dsc  