# ####################################################################################################################
# This compose file contains extra services required for certain workflows.
# E.g. some image analytics task require an external, long-running service for intermediate request. Such services should
# be placed here.
# ####################################################################################################################

version: '3.9'

services:

  profiling-image-caption-generator-ibm:
    image: codait/max-image-caption-generator
    container_name: profiling-image-caption-generator-ibm
    restart: always
    ports:
      - "6000:5000"
    networks:
      - diva_workflows

  profiling-image-object-detection-ibm:
    image: codait/max-object-detector
    container_name: profiling-image-object-detection-ibm
    restart: always
    ports:
      - "6001:5000"
    networks:
      - diva_workflows

networks:
  diva_workflows:
    name: diva_workflows
