filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: ["message"]
      target: "logMessage"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "diva-filebeat-%{+yyyy.MM.dd}"
      when.or:
        - regexp:
            container.image.name: "ghcr.io/fraunhoferisst/diva/.*"

logging.json: false
logging.metrics.enabled: false