kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: diva-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.22.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 8000
    hostPort: 8000
    protocol: TCP  
  - containerPort: 8080
    hostPort: 7000
    protocol: TCP  
  - containerPort: 443
    hostPort: 443
    protocol: TCP