openapi: 3.0.0
info:
  description: "Policy Management Service is responsible for policy related operations"
  version: 1.0.0
  title: Policy Management API
servers:
  - url: http://localhost:3013
tags:
  - name: decisions
    description: Operations for policy enforcements
  - name: collector
    description: CRUD operations on policies
paths:
  /decision:
    post:
      tags:
        - decisions
      summary: Get policy decision on operation
      description: Asks the policy decision endpoint for a decision on a certain operation. The request body 
        must contain the actor, the method, the url and the type associated with the operation the decision should
        be made on. 
      responses:
        200:
          description: OK