openapi: 3.0.0

info:
  description: "The Analytics Service is connected to the Elasticsearch in DIVA. It uses the ES DSL to generate interesting metrics about entities and other stuff."
  version: 1.0.0
  title: Analytics Assistant API

servers:
  - url: http://localhost:3007

tags:
  - name: Global Metrics
    description: Analytics that return global DIVA metrics
  - name: Resource Metrics
    description: Analytics that return specifc metrics regarding resources

paths:

  /analytics/distributionOfEntities:
    parameters:
      - $ref: "#/components/parameters/divaHeader"
    get:
      tags:
        - Global Metrics
      summary: Returns the percentual and absolut distribution of an entities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object 
        '4XX':
          $ref: "#/components/responses/Error"
        '5XX':
          $ref: "#/components/responses/Error"

  /analytics/distributionOfResourceTypes:
    parameters:
      - $ref: "#/components/parameters/divaHeader"
    get:
      tags:
        - Resource Metrics
      summary: Returns the percentual and absolut distribution of resource types
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object 
        '4XX':
          $ref: "#/components/responses/Error"
        '5XX':
          $ref: "#/components/responses/Error"        

  /analytics/distributionOfResourceMimeTypes:
    parameters:
      - $ref: "#/components/parameters/divaHeader"
    get:
      tags:
        - Resource Metrics
      summary: Returns the percentual and absolut distribution of the mime type
        of file resources
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object 
        '4XX':
          $ref: "#/components/responses/Error"
        '5XX':
          $ref: "#/components/responses/Error"

  /analytics/entities/{id}/reviews:
    parameters:
      - $ref: "#/components/parameters/divaHeader"
      - $ref: "#/components/parameters/entityIdParam"
    get:
      tags:
        - Entity reviews metrics
      summary: Returns the entity reviews statistics
      description: Returns the average rating of an entity calculated on reviews and the total number of reviews for the given entity,
        empty response is returned, if no reviews are available.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  avgRating:
                    type: number
                    title: Average rating
                    description: Average entity rating
                  reviewsCount:
                    type: number
                    title: Number of reviews
                    description: Number of written reviews for the given entity
        '4XX':
          $ref: "#/components/responses/Error"
        '5XX':
          $ref: "#/components/responses/Error"

components:

  schemas:
    
    EntityId:
      title: Entity ID
      description: Unique identifier of an entity
      type: string
      example: "resource:uuid:asdsad4d1fcb08-b894-4bdf-b662-0f105d597189"
      pattern: "^.+:uuid:[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[089ab][0-9a-f]{3}-[0-9a-f]{12}$"

    Error:
      type: object
      additionalProperties: false
      required:
        - type
        - message
        - code
      properties:
        type:
          description: Description of the error type
          type: string
        message:
          description: Description of the error
          type: string
        code:
          description: Erro status code
          type: number
          format: int32
        errors:
          description: JSON Schema validation errors
          type: array
          items:
            type: object
  
  responses:
    
    Error:
      description: Internal error
      content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"


  parameters:

    divaHeader:
      in: header
      description: The system specific stringified object whit relevant data like actorId, token etc.
      name: x-diva
      required: true
      schema:
        type: string

    entityIdParam:
      in: path
      description: Existing identifier of the resource that should be used by the operation
      name: id
      schema:
        $ref: "#/components/schemas/EntityId"
      required: true  
