module.exports = {
  DIVA_DB_NAME: process.env.MONGO_DB_NAME ?? "divaDb",
  entityTypes: {
    ENTITY: "entity",
    RESOURCE: "resource",
    ASSET: "asset",
    FOLDER: "folder",
    REVIEW: "review",
    SERVICE: "service",
    DESTROY_CLAIM: "destroyclaim",
    USER: "user",
    PUBLISHER: "publisher",
    SYSTEM_ENTITY: "systemEntity",
    POLICY: "policy",
    RULE: "rule",
    SCHEMA: "schema",
    ASYNCAPI: "asyncapi",
  },
  collectionsNames: {
    ENTITY_COLLECTION_NAME: "entities",
    SYSTEM_ENTITY_COLLECTION_NAME: "systemEntities",
    RESOURCE_COLLECTION_NAME: "resources",
    ASSETS_COLLECTION_NAME: "assets",
    FOLDERS_COLLECTION_NAME: "folders",
    REVIEWS_COLLECTION_NAME: "reviews",
    USERS_COLLECTION_NAME: "users",
    PUBLISHERS_COLLECTION_NAME: "publishers",
    SERVICES_COLLECTION_NAME: "services",
    DESTROY_CLAIM_COLLECTION_NAME: "destroyclaims",
    HISTORIES_COLLECTION_NAME: "histories",
    RULES_COLLECTION_NAME: "rules",
    SCHEMATA_COLLECTION_NAME: "schemata",
    POLICIES_COLLECTION_NAME: "policies",
    ASYNCAPI_COLLECTION_NAME: "asyncapis",
  },
};
