name: Build and publish airflow image

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "core/airflow/dags"
      - "core/airflow/plugins"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "core/airflow/dags"
      - "core/airflow/plugins"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: diva-airflow
  SERVICE_PATH: core/airflow

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: ./composite/action.yml
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get-version
        id: package-version
        run: echo ::set-output name=VERSION::$(python ${{ env.SERVICE_PATH }}/setup.py --version)

      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          context: ${{ env.SERVICE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}