name: Build and publish text-keyword-extractor image

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "faas/text-keyword-extractor/**"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "faas/text-keyword-extractor/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  DIVA_DOCKER_CONTEXT: faas/text-keyword-extractor
  IMAGE_NAME: text-keyword-extractor
  DIVA_DOCKERFILE_PATH: faas/text-keyword-extractor/Dockerfile
  SERVICE_PATH: faas/text-keyword-extractor
  SERVICE_RELATIVE_PATH: text-keyword-extractor

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: get-version
        id: package-version
        run: echo ::set-output name=VERSION::$(python ${{ env.SERVICE_PATH }}/setup.py --version)


      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: ${{ env.DIVA_DOCKER_CONTEXT }}
          file: ${{ env.DIVA_DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SERVICE_NAME=${{ env.SERVICE_RELATIVE_PATH }}