name: Build and publish web-client image

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "web-client/**"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "web-client/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: web-client
  DIVA_DOCKER_CONTEXT: web-client
  DIVA_DOCKERFILE_PATH: web-client/Dockerfile
  SERVICE_PATH: web-client
  SERVICE_RELATIVE_PATH: undefined

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ${{ env.SERVICE_PATH }}

      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.current-version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: ${{ env.DIVA_DOCKER_CONTEXT }}
          file: ${{ env.DIVA_DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SERVICE_NAME=${{ env.SERVICE_RELATIVE_PATH }}
