name: Build and publish image-text-extractor image

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "faas/image-text-extractor/**"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "faas/image-text-extractor/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  DIVA_DOCKER_CONTEXT: faas/image-text-extractor
  IMAGE_NAME: image-text-extractor
  DIVA_DOCKERFILE_PATH: faas/image-text-extractor/Dockerfile
  SERVICE_PATH: faas/image-text-extractor
  SERVICE_RELATIVE_PATH: image-text-extractor

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get-version
        id: package-version
        run: echo ::set-output name=VERSION::$(python ${{ env.SERVICE_PATH }}/setup.py --version)


      - name: Log in to the Container registry
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@b2391d37b4157fa4aa2e118d643f417910ff3242
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.VERSION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@7f9d37fa544684fb73bfe4835ed7214c255ce02b
        with:
          context: ${{ env.DIVA_DOCKER_CONTEXT }}
          file: ${{ env.DIVA_DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SERVICE_NAME=${{ env.SERVICE_RELATIVE_PATH }}