name: Build and publish diva-faas-personal-data-evaluation image

on:
  push:
    branches: ["master", "dev"]
    paths:
      - "faas/personal-data-evaluation/**"
      - "!*.md"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - "faas/personal-data-evaluation/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: diva-faas-personal-data-evaluation
  DIVA_DOCKER_CONTEXT: core
  DIVA_DOCKERFILE_PATH: faas/personal-data-evaluation/Dockerfile
  SERVICE_PATH: faas/personal-data-evaluation

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ${{ env.SERVICE_PATH }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.current-version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ env.DOCKER_CONTEXT }}
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
