name: Build and publish keywords-similarity-hash-generator image

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]
    paths:
      - "faas/keywords-similarity-hash-generator/**"
      - "!*.md"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "faas/keywords-similarity-hash-generator/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: keywords-similarity-hash-generator
  DIVA_DOCKER_CONTEXT: faas/keywords-similarity-hash-generator
  DIVA_DOCKERFILE_PATH: faas/keywords-similarity-hash-generator/Dockerfile
  SERVICE_PATH: faas/keywords-similarity-hash-generator
  SERVICE_RELATIVE_PATH: keywords-similarity-hash-generator

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: ${{ env.SERVICE_PATH }}

      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@57396166ad8aefe6098280995947635806a0e6ea
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.package-version.outputs.current-version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
        with:
          context: ${{ env.DIVA_DOCKER_CONTEXT }}
          file: ${{ env.DIVA_DOCKERFILE_PATH }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: SERVICE_NAME=${{ env.SERVICE_RELATIVE_PATH }}
