name: Build and publish +name+ image

on:
  push:
    branches: ['Add_ci_pipeline']
    paths:
      - "+path+/**"
      - "!*.md"
  pull_request:
    branches: [ 'Add_ci_pipeline' ]
    paths:
      - "+path+/**"
      - "!*.md"

env:
  REGISTRY: ghcr.io/fraunhoferisst/diva
  IMAGE_NAME: +name+
  SERVICE_PATH: +path+

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/composite